"""initial schema

Revision ID: 9da934854408
Revises: 
Create Date: 2026-10-02 17:54:05.869015
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9da934854408'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_paths',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=160), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_career_paths')),
    sa.UniqueConstraint('slug', name=op.f('uq_career_paths_slug'))
    )
    op.create_table('ingestion_jobs',
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('trigger', sa.String(length=40), server_default='MANUAL', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('records_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index(op.f('ix_ingestion_jobs_status'), 'ingestion_jobs', ['status'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_checksum', sa.String(length=64), nullable=True),
    sa.Column('document_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents')),
    sa.UniqueConstraint('source_url', name=op.f('uq_knowledge_documents_source_url'))
    )
    op.create_index(op.f('ix_knowledge_documents_content_checksum'), 'knowledge_documents', ['content_checksum'], unique=False)
    op.create_table('legal_topics',
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=160), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_topics')),
    sa.UniqueConstraint('slug', name=op.f('uq_legal_topics_slug'))
    )
    op.create_table('opportunity_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_opportunity_categories_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_opportunity_categories_slug'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('official_domain', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_type', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_official_domain'), 'organizations', ['official_domain'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name'))
    )
    op.create_table('source_fetch_logs',
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('records_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_fetch_logs'))
    )
    op.create_index(op.f('ix_source_fetch_logs_source_name'), 'source_fetch_logs', ['source_name'], unique=False)
    op.create_index(op.f('ix_source_fetch_logs_status'), 'source_fetch_logs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=120), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('career_skills',
    sa.Column('career_path_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('importance', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['career_path_id'], ['career_paths.id'], name=op.f('fk_career_skills_career_path_id_career_paths'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_career_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('career_path_id', 'skill_id', name=op.f('pk_career_skills'))
    )
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_document_chunks_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_document_chunk_ordinal')
    )
    op.create_table('legal_documents',
    sa.Column('legal_topic_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('publisher', sa.String(length=240), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('content_excerpt', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['legal_topic_id'], ['legal_topics.id'], name=op.f('fk_legal_documents_legal_topic_id_legal_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_documents'))
    )
    op.create_index(op.f('ix_legal_documents_legal_topic_id'), 'legal_documents', ['legal_topic_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deadline_reminders_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('digest_frequency', sa.String(length=40), server_default='DAILY', nullable=False),
    sa.Column('category_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', name='uq_notification_preferences_user')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('opportunity_type', sa.String(length=40), nullable=False),
    sa.Column('qualification', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=240), nullable=True),
    sa.Column('experience_required', sa.String(length=200), nullable=True),
    sa.Column('age_limit', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('work_mode', sa.String(length=40), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('stipend_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('compensation_currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('application_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('result_date', sa.Date(), nullable=True),
    sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('documents_required', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selection_process', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('official_url', sa.String(length=2048), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=60), nullable=True),
    sa.Column('notification_number', sa.String(length=160), nullable=True),
    sa.Column('identity_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=40), server_default='UPCOMING', nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("opportunity_type IN ('GOVERNMENT_JOB', 'PRIVATE_JOB', 'INTERNSHIP', 'APPRENTICESHIP', 'SCHOLARSHIP', 'FELLOWSHIP', 'EXAM', 'ENTRANCE_EXAM', 'HACKATHON', 'COMPETITION', 'RESEARCH', 'GOVERNMENT_SCHEME', 'SKILL_PROGRAM', 'OTHER')", name=op.f('ck_opportunities_valid_opportunity_type')),
    sa.CheckConstraint("status IN ('UPCOMING', 'OPEN', 'CLOSING_SOON', 'CLOSED', 'CANCELLED', 'RESULT_AVAILABLE', 'UPDATED')", name=op.f('ck_opportunities_valid_opportunity_status')),
    sa.ForeignKeyConstraint(['category_id'], ['opportunity_categories.id'], name=op.f('fk_opportunities_category_id_opportunity_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_opportunities_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('organization_id', 'notification_number', 'closing_date', name='uq_opportunity_notification_identity')
    )
    op.create_index(op.f('ix_opportunities_closing_date'), 'opportunities', ['closing_date'], unique=False)
    op.create_index(op.f('ix_opportunities_location'), 'opportunities', ['location'], unique=False)
    op.create_index('ix_opportunities_opening_date', 'opportunities', ['opening_date'], unique=False)
    op.create_index(op.f('ix_opportunities_opportunity_type'), 'opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index('ix_opportunities_status_type', 'opportunities', ['status', 'opportunity_type'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index('uq_opportunities_identity_hash', 'opportunities', ['identity_hash'], unique=True, postgresql_where=sa.text('identity_hash IS NOT NULL'))
    op.create_index('uq_opportunities_official_url', 'opportunities', ['official_url'], unique=True, postgresql_where=sa.text('official_url IS NOT NULL'))
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience_summary', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preferred_career', sa.String(length=200), nullable=True),
    sa.Column('preferred_industry', sa.String(length=200), nullable=True),
    sa.Column('preferred_location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.String(length=40), nullable=True),
    sa.Column('government_private_preference', sa.String(length=40), nullable=True),
    sa.Column('internship_preference', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exam_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_profiles_user_id'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_user_roles_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('user_skills',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('proficiency', sa.String(length=40), nullable=True),
    sa.Column('years_experience', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id', name=op.f('pk_user_skills'))
    )
    op.create_table('applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=40), server_default='PLANNED', nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED', 'APPLIED', 'ASSESSMENT', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN')", name=op.f('ck_applications_valid_application_status')),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_applications_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('chat_session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('USER', 'ASSISTANT', 'SYSTEM')", name=op.f('ck_chat_messages_valid_chat_role')),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_chat_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_chat_session_id'), 'chat_messages', ['chat_session_id'], unique=False)
    op.create_table('opportunity_documents',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document_url', sa.String(length=2048), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_documents_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_documents'))
    )
    op.create_index(op.f('ix_opportunity_documents_opportunity_id'), 'opportunity_documents', ['opportunity_id'], unique=False)
    op.create_table('opportunity_skills',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_skills_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_opportunity_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'skill_id', name=op.f('pk_opportunity_skills'))
    )
    op.create_table('opportunity_sources',
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('source_type', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_sources_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_sources')),
    sa.UniqueConstraint('opportunity_id', 'source_url', name='uq_opportunity_source_url')
    )
    op.create_index(op.f('ix_opportunity_sources_opportunity_id'), 'opportunity_sources', ['opportunity_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=80), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_recommendations_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_recommendation_user_opportunity')
    )
    op.create_index('ix_recommendations_user_score', 'recommendations', ['user_id', 'score'], unique=False)
    op.create_table('saved_opportunities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_saved_opportunities_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_opportunities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'opportunity_id', name=op.f('pk_saved_opportunities'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_opportunities')
    op.drop_index('ix_recommendations_user_score', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_opportunity_sources_opportunity_id'), table_name='opportunity_sources')
    op.drop_table('opportunity_sources')
    op.drop_table('opportunity_skills')
    op.drop_index(op.f('ix_opportunity_documents_opportunity_id'), table_name='opportunity_documents')
    op.drop_table('opportunity_documents')
    op.drop_index(op.f('ix_chat_messages_chat_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_applications_user_status', table_name='applications')
    op.drop_table('applications')
    op.drop_table('user_skills')
    op.drop_table('user_roles')
    op.drop_table('profiles')
    op.drop_index('uq_opportunities_official_url', table_name='opportunities', postgresql_where=sa.text('official_url IS NOT NULL'))
    op.drop_index('uq_opportunities_identity_hash', table_name='opportunities', postgresql_where=sa.text('identity_hash IS NOT NULL'))
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index('ix_opportunities_status_type', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_opportunity_type'), table_name='opportunities')
    op.drop_index('ix_opportunities_opening_date', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_location'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_closing_date'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_legal_documents_legal_topic_id'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('career_skills')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_fetch_logs_status'), table_name='source_fetch_logs')
    op.drop_index(op.f('ix_source_fetch_logs_source_name'), table_name='source_fetch_logs')
    op.drop_table('source_fetch_logs')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_official_domain'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('opportunity_categories')
    op.drop_table('legal_topics')
    op.drop_index(op.f('ix_knowledge_documents_content_checksum'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_ingestion_jobs_status'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_table('career_paths')
    # ### end Alembic commands ###